### PR TITLE
HAWKULAR-762 - Moved nest to the main Hawkular repository.

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
This is now for review, but should not be merged yet, as it contains a reference to Hawkular 1.0.7.Alpha-SNAPSHOT. Once the related commit is merged there, this will be updated. Everything else should remain the same.

**Comment by jpkrohling** [comment]
By the way, the build is failing due to the missing -SNAPSHOT artifact.

**Comment by jmazzitelli** [comment]
I wonder if this is going to be a problem now that we have bus dependent on the hawkular repo builds? Isn't that a circular dependency now? Because won't kettle need the bus, too? Seems like having the nest in hawkular repo is introducing a bad circular dependency.

**Comment by jpkrohling** [comment]
Not really, as only the samples are dependent. So, Bus itself is not dependent on Hawkular, and Hawkular does not (will never?) depend on a sample from Bus.

**Comment by jmazzitelli** [comment]
The hawkular repo PR has been merged, so I think this is ready to be merged now

**Comment by jmazzitelli** [comment]
@jpkrohling this PR still has "Do Not Merge Yet" label, so I will not merge. I'll let you decide if it is OK to merge.

**Pull request merged**
